name: hasan_utils
description: A set of commonly used utilities for faster Flutter development.
version: 1.2.4
homepage: https://github.com/HasanAlyazidi/hasan_utils

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1
  dio: ^5.7.0
  fast_localization: ^1.0.0
  stack_trace: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
